### ISSUE TITLE
Code:[ESReader-02], Description:[index不存在.]

### ISSUE THREAD

**Issue by workerzyh** [liufei96/datax-elasticsearch#1]
为什么我的索引存在，kibana中都能查到数据，但是该程序运行就报错索引不存在
kibana中查询结果：
"hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "bank_trace_log",
        "_type" : "_doc",
        "_id" : "oN55zHcBhH6jcM-b5qzt",
        "_score" : 1.0,
datax运行结果：
2021-03-06 16:19:39.520 [job-0] INFO  EsReader$Job - index:[bank_trace_log], type:[_doc]
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2021-03-06 16:19:39.694 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[ESReader-02], Description:[index不存在.]

**Comment by liufei96** [comment]
你的es是什么版本？？

**Comment by workerzyh** [comment]
> 你的es是什么版本？？

7.5的

**Comment by liufei96** [comment]
配置文件方面发一下，我这边帮你看一下？

**Comment by workerzyh** [comment]
> 配置文件方面发一下，我这边帮你看一下？

方便加微信吗，微信沟通下？

**Comment by liufei96** [comment]
18855993840。我微信




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liufei96/datax-elasticsearch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 晚上8:49
收件人:&nbsp;"liufei96/datax-elasticsearch"<datax-elasticsearch@noreply.github.com&gt;;
抄送:&nbsp;"刘飞"<1583409404@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [liufei96/datax-elasticsearch] Code:[ESReader-02], Description:[index不存在.] (#1)





  
配置文件方面发一下，我这边帮你看一下？
  
方便加微信吗，微信沟通下？

**Comment by liufei96** [comment]
已经找到原因了，是因为使用了账号和密码那段认证有问题。我之前使用的es没有账号和密码的，所以之前的没有测试到。已修复
